---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-dirs:
    - ci
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - govet
    - revive
run:
  issues-exit-code: 0
linters-settings:
  gosec:
    severity: medium
    confidence: high
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    enable:
      # report about shadowed variables
      - shadowing
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 30
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
