apiVersion: v1
kind: Pod
metadata:
  name: test-pod-cowsay
  namespace: vk
  annotations:
    slurm-job.knoc.io/flags: "--job-name=test-pod-cfg -t 2800  --ntasks=8 --nodes=1 --mem-per-cpu=2000"
spec:
  restartPolicy: Never
  containers:
  - image: docker://ghcr.io/grycap/cowsay 
    command: ["/bin/sh"]
    args: ["-c",  "\"touch /tmp/test.txt && sleep 60 && echo \\\"hello muu\\\" | /usr/games/cowsay \" " ]
    imagePullPolicy: Always
    name: cowsayo
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/hostname: test-vk
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
