name: build-image

on:
  push:
    tags:
      - "*"
permissions:
  contents: read
  packages: write
jobs:
  slurm-sidecar:
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        #run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base image
        uses: docker/build-push-action@v5
        with:
          context: ./
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink-sidecar-slurm/interlink-sidecar-slurm:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/interlink-sidecar-slurm/interlink-sidecar-slurm:latest
          file: ./docker/Dockerfile
          platforms: linux/amd64, linux/arm64